<?php

namespace GOLEM\GolemFaucetBundle\Repository;

/**
 * UserCheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCheckRepository extends \Doctrine\ORM\EntityRepository
{
}
